deployment:
  tasks:
    - export DEPLOYPATH=/home/bellenai/public_html
    - /bin/cp * $DEPLOYPATH
    - /usr/bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /usr/bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
